//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicTransport.Client.Services.Login {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Services.Login.ILoginService")]
    public interface ILoginService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/RequestLogin", ReplyAction="http://tempuri.org/ILoginService/RequestLoginResponse")]
        PublicTransport.Services.DataTransfer.UserInfo RequestLogin(PublicTransport.Services.DataTransfer.LoginData loginData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILoginService/RequestLogin", ReplyAction="http://tempuri.org/ILoginService/RequestLoginResponse")]
        System.Threading.Tasks.Task<PublicTransport.Services.DataTransfer.UserInfo> RequestLoginAsync(PublicTransport.Services.DataTransfer.LoginData loginData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoginServiceChannel : PublicTransport.Client.Services.Login.ILoginService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceClient : System.ServiceModel.ClientBase<PublicTransport.Client.Services.Login.ILoginService>, PublicTransport.Client.Services.Login.ILoginService {
        
        public LoginServiceClient() {
        }
        
        public LoginServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PublicTransport.Services.DataTransfer.UserInfo RequestLogin(PublicTransport.Services.DataTransfer.LoginData loginData) {
            return base.Channel.RequestLogin(loginData);
        }
        
        public System.Threading.Tasks.Task<PublicTransport.Services.DataTransfer.UserInfo> RequestLoginAsync(PublicTransport.Services.DataTransfer.LoginData loginData) {
            return base.Channel.RequestLoginAsync(loginData);
        }
    }
}
